name: My First Workflow

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "Hello, Github Actions!"

      - name: Print another message
        run: echo "Rupesh Ji"

  say-bye:
    runs-on: ubuntu-latest

    steps:
      - name: Print bye
        run: echo "Goodbye from second job"

  pr-job:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - name: Print PR event
        run: echo "This job runs only for Pull Requests"

      - name: Show PR details
        run: |
          echo "PR Title: ${{ github.event.pull_request.title }}"
          echo "PR Author: ${{ github.event.pull_request.user.login }}"